### ISSUE TITLE
tugas.html

### ISSUE THREAD

**Issue by giovandy1** [sumbayak/batakgroup#2]

**Comment by ayamkampus1** [comment]
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>tugas</title>
    <link rel="stylesheet" type="text/css" href="style.css">
    <link rel="shortcut icon" href="https://www.flaticon.com/search?word=script">
</head>

<body>
    <header>
        <div class="main">
            <div class="logo"><img src="gambar1.png" alt=""></div>
            <ul>
                <li><a href="#kt1">HOME</a></li>
                <li><a href="#">ABOUT US</a></li>
                <li><a href="#">GALLERY</a></li>
                <li><a href="#">SERVICE</a></li>
                <li><a href="#">BLOG</a></li>
                <li><a href="#cn">CONTACT</a></li>
            </ul>
        </div>
    </header>
    <div class="back">
        <img src="13.jpg">
    </div>

    <div class="button">
        <a href="#" class="btn1">GET MORE !</a>
        <a href="#" class="btn2">PURCAHASE NOW!</a>
    </div>

    <div class="title">
        <h2>ONETWO <span>CODE</span><br> WEBSITE</h2>
        <p class="p">Profesional Creativity Clean Featured Webiste Template<br> For Bussiness let's Star an AWESOME PROJECT! </p>
    </div>

    <div class="ktk">
        <div class="kotak1">
            <img src="11.png" alt="" width="50px" height="50px">
            <h3>Unlimited Layout</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. totam!</p>
        </div>
        <div class="kotak2">
            <img src="5.png" alt="" width="50px" height="50px">
            <h3 id="kt1">Unlimited Layout</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. totam!</p>
        </div>
        <div class="kotak3">
            <img src="save.png" alt="" width="50px" height="50px">
            <h3>Unlimited Layout</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. totam!</p>
        </div>
        <div class="kotak4">
            <img src="group.png" alt="" width="50px" height="50px">
            <h3>Unlimited Layout</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. totam!</p>
        </div>

    </div>

    <div class="button2">
        <a href="https://www.petanikode.com/" class="btn3">read more</a>
    </div>

    <div id="cn" class="close">
        <div class="awal">
            <img src="" alt="">
            <h3>ONE TWO CODE FRONT END WEB</h3>
            <h2>Easy Way To learn Front End Web Development</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores animi .</p>
        </div>
        <div class="tengah">
            <img class="r" src="23.jpg" alt="" width="300px" height="150px">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores animi</p>
        </div>
        <div class="terakhir">
            <img class="gmb" src="43.jpg" alt="" width="300px" height="150px">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Asperiores animi</p>
        </div>
    </div>

    <footer>
        <p>Copyright@2020</p>
        <p>Design&Developed by BATAK ONETWO CODE</p>

    </footer>



</body>

</html>
